export const LocationTitlesFullList: {[key: string]:string} = {
  'Avtoto' : 'Автово',
  'Admiralteyskaya' : 'Адмиралтейская',
  'Akademicheskaya' : 'Академическая',
  'Baltiyskaya' : 'Балтийская',
  'Bukharestskaya' :'Бухарестская',
  'Vasileostrovskaya' : 'Василеостровская',
  'Vladimirskaya' : 'Владимирская',
  'Volkovskaya' : 'Волковская',
  'Vyborgskaya' : 'Выборгская',
  'Gorkovskaya' : 'Горьковская',
  'GostinyDvor':'Гостиный двор',
  'GrazhdanskiyProspect' : 'Гражданский проспект',
  'Devaytkino' : 'Девяткино',
  'Dostoyevskaya' : 'Достоевская',
  'Elizarovskaya' : 'Елизаровская',
  'Zvezdnaya' :'Звёздная',
  'Zvenigorodskaya' : 'Звенигородская',
  'Petrogradskaya' : 'Петроградская',
  'Pionerskaya' : 'Пионерская',
  'Udelnaya' : 'Удельная',
  'UlitzaDybenko' : 'Улица Дыбенко',
  'Frunzenskaya' : 'Фрунзенская',
  'ChernayaRechka' : 'Черная речка',
  'Chernyshevskaya' : 'Чернышевская',
  'Chkalovskaya' : 'Чкаловская',
  'Electrosila' : 'Электросила',
};

export enum LocationTitlesFullListEn {
   Avtoto = 'Avtoto',
Admiralteyskaya = 'Admiralteyskaya',
Akademicheskaya = 'Akademicheskaya',
Baltiyskaya = 'Baltiyskaya',
Bukharestskaya ='Bukharestskaya',
Vasileostrovskaya = 'Vasileostrovskaya',
Vladimirskaya = 'Vladimirskaya',
Volkovskaya = 'Volkovskaya',
Vyborgskaya = 'Vyborgskaya',
Gorkovskaya = 'Gorkovskaya',
GostinyDvor='GostinyDvor',
GrazhdanskiyProspect = 'GrazhdanskiyProspect',
Devaytkino = 'Devaytkino',
Dostoyevskaya = 'Dostoyevskaya',
Elizarovskaya = 'Elizarovskaya',
Zvezdnaya ='Zvezdnaya',
Zvenigorodskaya = 'Zvenigorodskaya',
Petrogradskaya = 'Petrogradskaya',
Pionerskaya = 'Pionerskaya',
Udelnaya = 'Udelnaya',
UlitzaDybenko = 'UlitzaDybenko',
Frunzenskaya = 'Frunzenskaya',
ChernayaRechka = 'ChernayaRechka',
Chernyshevskaya = 'Chernyshevskaya',
Chkalovskaya = 'Chkalovskaya',
Electrosila = 'Electrosila',
}
